language: objective-c
osx_image: xcode7.2
script:
  - set -o pipefail
  - xcodebuild test -scheme EggsBenedict -destination "name=iPhone 6s Plus" -sdk iphonesimulator | xcpretty -c
notifications:
  email: false
